### ISSUE TITLE
ViaVersion Dependency

### ISSUE THREAD

**Issue by InfinityAspire** [xNitrate/StreamLine#1]
Not so much a bug as it is a better handling of this specific dependency.

Would it be possible to remove the hard dependency on ViaVersion?

It's more stable for the server and the players to use the Via plugins on the backend servers rather than the Proxy, meaning anyone running this way, [the recommended way by the Via plugin devs], cannot use Streamline.

**Comment by xNitrate** [comment]
I will look into this. I actually planned on doing this, just forgot. :P

**Comment by xNitrate** [comment]
Done. Check the Spigot page for new download. :P
